### ISSUE TITLE
javax/xml/bind/JAXBException Issues running Jacklyn app on java 9

### ISSUE THREAD

**Issue by sylvanusi** [tcdng/jacklyn-app#1] opened 2019-01-19 20:54 UTC
[jacklyn_error.txt](https://github.com/tcdng/jacklyn-app/files/2775947/jacklyn_error.txt)

Unable to start the jacklyn app on a java 9 environment. See stack trace below:

Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at com.tcdng.unify.core.util.TypeUtils$TypeRepositoryImpl.getAnnotatedClasses(TypeUtils.java:88)
        at com.tcdng.unify.core.util.UnifyConfigUtils.readConfigFromTypeRepository(UnifyConfigUtils.java:125)
        at com.tcdng.unify.core.Unify.doStartup(Unify.java:128)
        at com.tcdng.unify.core.Unify.main(Unify.java:70)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more

Regards.

**Comment by tcdng** [comment] 2019-01-20 21:28
This issue is caused by JAXB packages not included in classpath by default on Java 9 and 10. Fixed in release 1.0.1.

Release 1.0.1:
1. Resolves Java version and JAXB compatibility issues.
2. Runs on Java 7, 8, 9 and 10.

**Closed as completed by tcdng** 2019-01-20 21:28 UTC
